export {
  DocumentDuplicateIcon as CollectionIcon,
  DocumentPlusIcon as CreateDocumentIcon,
  ArrowUpTrayIcon as PublishIcon,
  ArchiveBoxIcon as ArchiveIcon,
  DocumentIcon as DocumentIcon,
  PencilIcon as EditIcon,
  TrashIcon as TrashIcon,
  LinkIcon as LinkIcon,
  ArrowLongRightIcon as ArrowRightIcon,
  CircleStackIcon as ContentIcon,
  PlusIcon as PlusIcon,
  ArrowUturnLeftIcon as TurnLeftIcon,
  ArrowUturnRightIcon as TurnRightIcon,
  XMarkIcon as XIcon,
} from '@heroicons/react/24/outline'
