name: Checks

on:
  push:
    branches:
      - '*'

env:
  FORCE_COLOR: true

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-main-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-main-

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Build
        run: pnpm test
