name: Checks

on:
  push:
    branches:
      - '*'

env:
  FORCE_COLOR: true

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - uses: actions/cache@v4
        name: Setup shared cache
        with:
          path: ~/.cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Set pnpm cache dir
        run: pnpm config set store-dir ~/.cache/pnpm

      - name: Install dependancies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Run generation scripts
        run: pnpm generate

      - name: Install playwright binaries
        working-directory: ./examples/fields
        run: pnpm playwright install --with-deps

      - name: Run tests
        run: pnpm test
        env:
          FIREBASE_APIKEY: 'test'
          FIREBASE_AUTHDOMAIN: 'test'
          FIREBASE_PROJECTID: ${{ secrets.FIREBASE_PROJECTID }}
          FIREBASE_STORAGEBUCKET: 'test'
          FIREBASE_MESSAGINGSENDERID: 'test'
          FIREBASE_APPID: 'test'
